import type { Metadata } from "next";

import { RootLayoutComponent } from "@repo/shared";
import "./globals.css";

export const metadata: Metadata = {
  title: "سایت فروشگاهی",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return <RootLayoutComponent>{children}</RootLayoutComponent>;
}
